[tasks.build] # cargo make build
command = "wasm-pack"
args = ["build", "--dev", "--target", "web", "--out-name", "wasm", "--out-dir", "./static"]
watch = { ignore_pattern = "static/*" }

[tasks.serve] # cargo make serve
command = "miniserve"
args = ["./static", "-p", "3000", "--index", "index.html"]
